### PR TITLE
Add support to build for RTEMS targets

### PR DESCRIPTION
**Pull request by heshamelmatary**

### CODE REVIEW

**Comment by olajep** [comment]
Looks good to me (except no ChangeLog and the last commit is effectively a revert of the first but I'll fix that)

I would appreciate if
@jeremybennett
could comment on this before I apply.

@heshamelmatary
Were you able to work around the double alignment issue mentioned here:
https://github.com/adapteva/epiphany-gcc/pull/4

or do you still need `PARM_BOUNDARY 64` ?

// Ola

**Comment by heshamelmatary** [comment]
Regarding the double alignment issue, I was able to get around it from RTEMS, so don't worry about it.

**Comment by heshamelmatary** [comment]
Who should modify the ChangeLog? Please let me know if there are any issues because I'm waiting for this merge so that I can refer to this repo from RSB (RTEMS Source Builder) and submit patches.

**Comment by olajep** [comment]
Applied to epiphany-gcc-4.9 branch here:
30f4c63c9530628a5a131f5c5d08c8a0253c0772

**Pull request closed without merging**
