### PR TITLE
Fix FP register rename regression

### PR DESCRIPTION
**Pull request by olajep**
- config/epiphany/epiphany.md (stack_adjust_add_fp, stack_adjust_mov):  
  Use FP instead of hardcoded R15. Fixes regression introduced by  
  commit "(GPR_FP): Change to 11" (c4d6b17f514ef85f85811eecb514191216c19610)

### CODE REVIEW

**Comment by jeremybennett** [comment]
I'd like Joern (amylaar) to give a quick review of this.

**Comment by jeremybennett** [comment]
I've talked to Joern.  This change was introduced by Pierre Langlois as part of the software cache work and we're not clear why it was done. Reverting the change seems the right thing do, but if you make this change does the software cache still work?

I'm going to try to get hold of Pierre and also talk to other colleagues to find out more.

**Comment by olajep** [comment]
No **don't** revert it! if you do you have to revert more than that.

The FP r15-->r11 was done in other places too. This one breaks GCC b/c the hardcoded r15.
Hopefully there are no more hardcoded r15 stuff in the toolchain. But... maybe there is some old assembly code in newlib ?

Here's a test case:  
https://gist.github.com/olajep/f06fa1dc364857c28588

I don't know much about GCC's RTL but if you say:

```
(set (reg:SI GPR_SP)                                                                                                                                                      
    (plus:SI (reg:SI GPR_FP) (match_operand:SI 0 "arith_operand" "rL")))
```

you should emit the corresponding assembler code.

I guess this is a leftover from way back when there was no $fp, so you had to hardcode it.

I've tested this with your soft-cache examples on the Parallella, and it works.

**Comment by amylaar** [comment]
Actually, I changed the framepointer from r11 to r15 in 2013, in order to allow the efficient frame
manipulation necessary for the software cache.  Changing it back to r11 destroys the foundations
of the software cache.

**Comment by amylaar** [comment]
Note also that the ChangeLog is wrong.
First, "Use FP instead of hardcoded R15", is misleading, because "fp" is an alias for r11,
no less hardcoded that r15, and wrong when GPR_FP is restored to its proper value.
To make this something non-hard-coded, you'd need more elaborate output patterns, something like:
{ asm_fprintf (asm_out_file, "\tmov sp,r%d", GPR_FP); return ""; }
{ asm_fprintf (asm_out_file, "\tmov sp,%s", reg_names[GPR_FP]); return ""; }
{
  rtx xop[2];
  xop[0] = operands[0];
  xop[1] = hard_frame_pointer_rtx;
  output_asm_insn ("add sp,%1,%0", xop);
  return "";
}

Second, you are only addressing the regression in the consistency of the two patterns with the GPR_FP
definition.  You are not addressing the performance regression in the function prologue, nor the
regression in the frame pointer availability in r15 for the software cache code.

**Comment by T-J-Teru** [comment]
When you say:

> First, "Use FP instead of hardcoded R15", is misleading, because "fp" is an alias for r11,
> no less hardcoded that r15,

who is doing the aliasing here?  My understanding of this code was the it relied on the assembler to decide which register to use for `fp`.  As such `fp` is, in effect, a pseudo-architectural register, and so long as the assembler understands your ABI you'll always do the right thing.

The description "Use FP instead of hardcoded R15" is spot on, and is exactly what we should do.  It is for this reason that I believe this pull request is correct and should be merged.  This is a separate issue to the discussion of which register to use for `fp` in the ABI, which ever way that discussion resolves, this pull request should still be merged.

In your second point:

> You are not addressing the performance regression in the function prologue, nor the
> regression in the frame pointer availability in r15 for the software cache code.

Just so I have it clear (in my head) you're saying that the software cache will not function correctly if the `fp` register is changed back to `r11`?  Or are you saying it will function, just slower then it might do if `fp` was set to `r15`?

**Comment by amylaar** [comment]
On 29 October 2014 22:27, Andrew notifications@github.com wrote:

> When you say:
> 
> First, "Use FP instead of hardcoded R15", is misleading, because "fp" is
> an alias for r11,
> no less hardcoded that r15,
> 
> who is doing the aliasing here?

It's the assembler.  It's a marketing gimmick to make the processor look
more like an ARM.

> My understanding of this code was the it relied on the assembler to decide
> which register to use for fp. As such fp is, in effect, a
> pseudo-architectural register, and so long as the assembler understands
> your ABI you'll always do the right thing.
> 
> The assembler doesn't know about the ABI.
> 
> The description "Use FP instead of hardcoded R15" is spot on, and is
> exactly what we should do.
> 
> In your world, as you explained above.  As I explained above, that world is
> not the one we live in.
> 
> It is for this reason that I believe this pull request is correct and
> should be merged. This is a separate issue to the discussion of which
> register to use for fp in the ABI, which ever way that discussion
> resolves, this pull request should still be merged.
> 
> In your second point:
> 
> You are not addressing the performance regression in the function
> prologue, nor the
> regression in the frame pointer availability in r15 for the software cache
> code.
> 
> Just so I have it clear (in my head) you're saying that the software cache
> will not function correctly if the fp register is changed back to r11? Or
> are you saying it will function, just slower then it might do if fp was
> set to r15?
> 
> All the -fpic function prologues are slower since the change of GPR_FP
> change (the
> observable effect is that function calls are slower).
> The software cache will not be able to reliably find the return address,
> which is required
> to identify the functions belonging to active stack frames.  It might use a
> heuristic
> concept of the stack layout, but different optimization options, prima
> facie unrelated
> changes in the source code, and changes in the base GCC version can
> invalidate these,
> making the program behaviour random.

**Comment by olajep** [comment]
@amylaar @T-J-Teru 
Thanks for reviewing!

The change in `stack_adjust_mov` fixes this:  
(https://gist.github.com/olajep/f06fa1dc364857c28588)

```
000008fc <_print_route>:
     8fc:   74dc 2400   str fp,[sp,+0x1]
     900:   74ef 2402   mov fp,sp           <--
     904:   9b0b 2f92   mov r12,0xf9d8
     908:   9feb 3ff2   movt r12,0xffff
     90c:   d65d 2480   str lr,[sp],+r12
...
(not a single access to r15)
...
     aa4:   bcef 2402   mov sp,r15          <--
     aa8:   74cc 2400   ldr fp,[sp,+0x1]
     aac:   d44c 2600   ldr lr,[sp],+0x0
     ab0:   194f 0402   rts
     ab4:   0000        beq ab4 <_print_route+0x1b8>
    ...
```

**Comment by olajep** [comment]
I've updated the ChangeLog entry based on your comments.

Is this better?

// Ola

**Comment by olajep** [comment]
Fixed in 005a35955747a2da8a48afdbbe00d80a12e41dde

**Pull request closed without merging**
